language: python

python: 3.6

jobs:
  include:
    - stage: test examples/chatter
      script:
        - cd examples/chatter
        - pip install -r requirements.txt
        -  flake8 --config=.flake8/setup.cfg --mypy-config=.flake8/setup.cfg
