title: Channel.js
description: Simple Javascript front-end for Django Channels apps
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

# About/contact
author:
  name:       Pramod Kotipalli
  url:        http://pramodk.net/ 

gems:
  - jekyll-mentions
