version: "3"

##################################
### DEVELOPMENT DOCKER COMPOSE ###
##################################

services:

  # This is the web container running the Django development server
  web:
    # Build the container image from this directory
    build: .
    # Share this directory with the container so we can easily develop new code
    volumes:
      - .:/www
    # Share a port with the hose machine
    ports:
      - 8080:8080
    command: ["runserver", "0.0.0.0:8080"]
    depends_on:
      - postgres

  # This is the database container we are using
  postgres:
    image: postgres
    # Store postgres data in a volume so it will persist if the container is removed
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
