version: "3"

services:
  web:
    build: .
    volumes:
      - .:/www
    ports:
      - 8080:8080
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    depends_on:
      - migrate

  migrate:
    build: .
    volumes:
      - .:/www
    command: ["python", "manage.py", "migrate"]
