version: "3"

services:
  web:
    build: .
    volumes:
      - .:/www
    ports:
      - 8080:8080
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
